package com.suwadi.domain;

public enum UserType {
	// 0-STAFF
	// 1-SOCIETY_PRESIDENT
	// 2-SOCIETY_SECRETARY
	// 3-SOCIETY_TREASURES
	// 4-SOCIETY_MEMBER
	STAFF, SOCIETY_PRESIDENT, SOCIETY_SECRETARY, SOCIETY_TREASURER, SOCIETY_MEMBER
}
